export enum SpecialtyEnum {
    ANESTHESIOLOGIST = "ANESTHESIOLOGIST",
    CARDIOLOGIST = "CARDIOLOGIST",
    DERMATOLOGIST = "DERMATOLOGIST",
    ENDOCRINOLOGIST = "ENDOCRINOLOGIST",
    FAMILY_PHYSICIAN = "FAMILY_PHYSICIAN",
    GASTROENTEROLOGIST = "GASTROENTEROLOGIST",
    NEPHROLOGIST = "NEPHROLOGIST",
    NEUROLOGIST = "NEUROLOGIST",
    OBSTETRICIAN_GYNECOLOGIST = "OBSTETRICIAN_GYNECOLOGIST",
    OPHTHALMOLOGIST = "OPHTHALMOLOGIST",
    ORTHOPEDIC_SURGEON = "ORTHOPEDIC_SURGEON",
    PEDIATRICIAN = "PEDIATRICIAN",
    PSYCHIATRIST = "PSYCHIATRIST",
    RADIOLOGIST = "RADIOLOGIST",
    SURGEON = "SURGEON"
}