package com.example.enums;

public enum ESpecialty {
    ANESTHESIOLOGIST,
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    FAMILY_PHYSICIAN,
    GASTROENTEROLOGIST,
    NERPHOLOGIST,
    NEUROLOGIST,
    OPHTHALMOLOGIST,
    PEDIATRICIAN,
    RADIOLOGIST
}
